src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address_1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address_2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address_3 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address_4 = null;

    #[ORM\Column(nullable: true)]
    private ?int $zipcode = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

     /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function __toString()
    {
        return (string)$this->getId();
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getAddress1(): ?string
    {
        return $this->address_1;
    }

    public function setAddress1(string $address_1): self
    {
        $this->address_1 = $address_1;

        return $this;
    }

    public function getAddress2(): ?string
    {
        return $this->address_2;
    }

    public function setAddress2(?string $address_2): self
    {
        $this->address_2 = $address_2;

        return $this;
    }

    public function getAddress3(): ?string
    {
        return $this->address_3;
    }

    public function setAddress3(?string $address_3): self
    {
        $this->address_3 = $address_3;

        return $this;
    }

    public function getAddress4(): ?string
    {
        return $this->address_4;
    }

    public function setAddress4(?string $address_4): self
    {
        $this->address_4 = $address_4;

        return $this;
    }

}

src/Controller/OrderPanelController.php
<?php

namespace App\Controller;

use App\Entity\OrderDetails;
use App\Entity\OrderItems;
use App\Repository\OrderDetailsRepository;
use App\Repository\OrderItemsRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderPanelController extends AbstractController
{
    private $orderDetailRepository;
    private $orderItemsRepository;
    private $productRepository;

    public function __construct(OrderDetailsRepository $orderDetailRepository, OrderItemsRepository $orderItemsRepository, ProductRepository $productRepository)
    {
        $this->orderDetailRepository = $orderDetailRepository;
        $this->orderItemsRepository = $orderItemsRepository;
        $this->productRepository = $productRepository;
    }

    #[Route('/admin/order', name: 'app_order_panel')]
    public function index(): Response
    {
        return $this->render('Admin_interface/order_panel/index.html.twig', [
            'controller_name' => 'OrderPanelController',
            'order_details' => $this->orderDetailRepository->findAll(),
            'order_items' => $this->orderItemsRepository->findAll(),
        ]);
    }

    #[Route('/admin/order/{id}', name: 'app_order_detail')]
    public function show(OrderDetails $orderdetail): Response
    {
        return $this->render('Admin_interface/order_panel/show.html.twig', [
            'controller_name' => 'OrderPanelController',
            'order_detail' => $orderdetail,
            'order_items' => $this->orderItemsRepository->findByOrder($orderdetail),
            'products' => $this->productRepository->findAll(),
        ]);
    }
}

templates/Admin_interface/order_panel/index.html.twig
{% extends "/Admin_interface/base.html.twig" %}

{% block header1 %}Orders
{% endblock %}
{% block header2 %}Orders
{% endblock %}
{% block tile %}{% endblock %}

{% block body %}
	<div class="message">
		
	</div>
	<div class="card">
		<div class="card-header">
			<h3 class="card-title">All orders</h3>
			<div class="card-tools">
				<button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
					<i class="fas fa-minus"></i>
				</button>
				<button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
					<i class="fas fa-times"></i>
				</button>
			</div>
		</div>
		<div class="card-body p-0">
			<table class="table table-striped projects">
				<thead>
					<tr>
						<th class="text-center">
							ID
						</th>
						<th class="text-center">
							Customer
						</th>
						<th class="text-center">
							Total
						</th>
						<th class="text-center">
							Created Date
						</th>
						<th class="text-center">
							Updated Date
						</th>
						<th class="text-center">
							Status
						</th>
					</tr>
				</thead>
				<tbody>
					{% for order_detail in order_details %}
						<tr>
							<td class="text-center">
								<a href="{{ path('app_order_detail', {'id': order_detail}) }}">{{order_detail}}</a>
							</td>
							<td class="text-center">
								{{order_detail.user.firstname}}
								{{order_detail.user.lastname}}
							</td>
							<td class="text-center">
								{{ order_detail.total|format_currency("VND") }}
							</td>
							<td class="text-center">
								{{order_detail.createdat|format_datetime}}
							</td>
							<td class="text-center">
								{{order_detail.updatedat|format_datetime}}
							</td>
							<td class="text-center">
								{% if order_detail.status == 0 %}
									<span class="badge badge-warning">Pending</span>
								{% endif %}
								{% if order_detail.status == 1 %}
									<span class="badge badge-info">Processing</span>
								{% endif %}
								{% if order_detail.status == 2 %}
									<span class="badge badge-info">Shipped</span>
								{% endif %}
								{% if order_detail.status == 3 %}
									<span class="badge badge-success">Delivered</span>
								{% endif %}
								{% if order_detail.status == 4 %}
									<span class="badge badge-danger">Canceled</span>
								{% endif %}
							</td>
						</tr>
					</tbody>
				</tbody>
			</td class="text-center">
		</tr>
	{% endfor %}
</tbody></table></div><!-- /.card-body --></div>{% endblock %}

templates/Admin_interface/order_panel/show.html.twig
{% extends "/Admin_interface/base.html.twig" %}

{% block header1 %}Order #{{order_detail}}
{% endblock %}
{% block header2 %}Orders
{% endblock %}
{% block title %}Order #{{order_detail}}
{% endblock %}

{% block body %}

<form action="{{ path('app_order_change_status', {'id': order_detail}) }}" method="post">
	<div class="card">
		<div class="card-header">
			<h3 class="card-title">Order Detail</h3>

			<div class="card-tools">
				<button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
					<i class="fas fa-minus"></i>
				</button>
				<button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
					<i class="fas fa-times"></i>
				</button>
			</div>
		</div>
		<div class="card-body p-0">
			<table class="table table-striped projects">
				<tr>
					<th>ID</th>
					<td>{{order_detail.id}}</td>
				</tr>
				<tr>
					<th>First name</th>
					<td>{{order_detail.firstname}}</td>
				</tr>
				<tr>
					<th>Last name</th>
					<td>{{order_detail.lastname}}</td>
				</tr>
				<tr>
					<th>Phone Number</th>
					<td>{{order_detail.phone}}</td>
				</tr>
				<tr>
					<th>Email</th>
					<td>{{order_detail.email}}</td>
				</tr>
				<tr>
					<th>Address</th>
					<td>{{order_detail.address1}},
						{{order_detail.address2}},
						{{order_detail.address3}},
						{{order_detail.address4}}</td>
				</tr>
				<th>Zipcode</th>
				<td>{{order_detail.zipcode}}</td>
			</tr>
			<tr>
				<th>Created</th>
				<td>{{order_detail.createdat|format_datetime}}</td>
			</tr>
			<tr>
				<th>Last Updated</th>
				<td>{{order_detail.updatedat|format_datetime}}</td>
			</tr>
			<tr>
				<th>status</th>
				<td>
				{% if order_detail.status == 0 %}
						<span class="badge badge-warning">Pending</span>
					{% endif %}
					{% if order_detail.status == 1 %}
						<span class="badge badge-info">Processing</span>
					{% endif %}
					{% if order_detail.status == 2 %}
						<span class="badge badge-info">Shipped</span>
					{% endif %}
					{% if order_detail.status == 3 %}
						<span class="badge badge-success">Delivered</span>
					{% endif %}
					{% if order_detail.status == 4 %}
						<span class="badge badge-danger">Canceled</span>
					{% endif %}
				<select name="status" id="status">
					{% if order_detail.status == 0 %}
						<option value=0 selected>Pending</option>
						<option value=1>Processing</option>
						<option value=2>Shipped</option>
						<option value=3>Delivered</option>
						<option value=4>Canceled</option>
					{% endif %}
					{% if order_detail.status == 1 %}
						<option value=0>Pending</option>
						<option value=1 selected>Processing</option>
						<option value=2>Shipped</option>
						<option value=3>Delivered</option>
						<option value=4>Canceled</option>
					{% endif %}
					{% if order_detail.status == 2 %}
						<option value=0>Pending</option>
						<option value=1>Processing</option>
						<option value=2 selected>Shipped</option>
						<option value=3>Delivered</option>
						<option value=4>Canceled</option>
					{% endif %}
					{% if order_detail.status == 3 %}
						<option value=0>Pending</option>
						<option value=1>Processing</option>
						<option value=2>Shipped</option>
						<option value=3 selected>Delivered</option>
						<option value=4>Canceled</option>
					{% endif %}
					{% if order_detail.status == 4 %}
						<option value=0>Pending</option>
						<option value=1>Processing</option>
						<option value=2>Shipped</option>
						<option value=3>Delivered</option>
						<option value=4 selected>Canceled</option>
					{% endif %}
				</select>
				<h6 class="mt-2">Edit the stock of the products? <input type="checkbox" name="edit_product"></h6>
				</td>
			</tr>
			<tr>
				<th>Total</th>
				<td>{{order_detail.total|format_currency('VND')}}</td>
			</tr>
		</table>
	</div>
	<div class="m-3" ><button type="submit" class="btn bg-primary" method="post">Save</button></div>
</form>
<!-- /.card-body --></div><div class="card">
<div class="card-header">
	<h3 class="card-title">All items</h3>

	<div class="card-tools">
		<button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
			<i class="fas fa-minus"></i>
		</button>
		<button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
			<i class="fas fa-times"></i>
		</button>
	</div>
</div>
<div class="card-body p-0">
	<table class="table table-striped projects">
		<thead>
			<tr>
				<th class="text-center">
					ID
				</th>
				<th class="text-center">
					Name
				</th>
				<th class="text-center">
					Price
				</th>
				<th class="text-center">
					Quantity
				</th>
				<th class="text-center">
					Total
				</th>
			</tr>
		</thead>
		<tbody>
			{% for order_item in order_items %}
				{% for product in products %}
					{% if product == order_item.product %}
						<tr>
							<td class="text-center">
								<a href="{{ path('app_product_show_admin', {'id': product}) }}">{{product}}</a>
							</td>
							<td class="text-center">
								{{product.name}}
							</td>
							<td class="text-center">
								{{ product.price|format_currency("VND") }}
							</td>
							<td class="text-center">
								{{order_item.quantity}}
							</td>
							<td class="text-center">
								{{order_detail.total|format_currency("VND") }}
							</td>
						</tr>
					{% endif %}
				{% endfor %}
			</tbody>
		</tbody>
	</table>
</td class="text-center"></td><td class="project-actions text-center"></td></tr>{% endfor %}</tbody></table></div><!-- /.card-body --></div>{% endblock %}